server:
  port: 8084
  forward-headers-strategy: framework

logging:
  level:
    web: INFO

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

razorpay:
  key: rzp_test_tF42jI563EUWQE
  secret: eGakMHimSEH7Lzb1f002golU
