server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  security:
    user:
      name: root
      password: 9b59fa41af17f4ba66
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
